name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v4

        # Install .NET SDK
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'

        # Run tests
        # - name: Test
        #   run: dotnet test

        # Generate the website
        - name: Publish
          run: dotnet publish ./patch-history-app/patch-history-app.sln -c Release -o build --nologo

        - name: Copy index.html to 404.html for SPA fallback
          run: cp ./build/wwwroot/index.html ./build/wwwroot/404.html 

        # Update base href
        - name: Change base href for GitHub Pages
          run: |
            sed -i 's|<base href="/" />|<base href="/${{ github.repository }}/" />|' build/wwwroot/index.html
        
        # Check that the href was updated
        - name: Output index.html after base href fix
          run: cat ./build/index.html

        # Publish the website
        - name: Deploy to GitHub Pages
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_dir: ./build/
            publish_branch: gh-pages
            # allow_empty_commit: false
            # keep_files: false
            # force_orphan: true
            # TODO uncomment the following line if you have a custom domain name
            # cname: